### ISSUE TITLE
Minor annoyance: Can't leave Lightpad clicking on an empty area

### ISSUE THREAD

**Issue by justmadethisaccount** [libredeb/lightpad#23] opened 2021-05-28 03:03 UTC
This is a really nice launchpad for Linux, I'm using it on Fedora XFCE.
Anyways, what I noticed is that unless I open an app, I can't leave the app menu.  Even if I hit the shortcut again, nothing happens. It's not that big of a deal, but it's a bit annoying.  Thank you.

**Comment by libredeb** [comment] 2021-07-23 00:39
Hi @justmadethisaccount thanks you for contributing... I don't understand what do you mean with app menu. How can I reproduce this scenario? I need more info and details (Fedora release version, kernel version, xfce version, etc). To attend this issue.

I hope you can take some time to explain me this details. Regards!

**Comment by eagerestwolf** [comment] 2021-09-10 02:20
I get what @justmadethisaccount is saying, and I've noticed it as well. I'm on Xubuntu 20.04 (Kernel 5.11.0_34. XFCE 4.11). When you open Lightpad, you can't just click in an empty space to close it like you can with Launchpad on macOS or Slingscold/Slingswarm. You either have to open an app or exit with the escape key. I assume this was an intentional design decision to prevent accidentally closing Lightpad as was know to happen with Slingscold/Slingswarm. I only really noticed it because my desktop is running Linux, but my runabout computer is an M1 MacBook Pro.

**Comment by fossfreedom** [comment] 2021-12-26 15:49
Guessing from the commit description this commit probably should be looked at - if working reliable maybe merged?

**Comment by eagerestwolf** [comment] 2021-12-28 03:17
@fossfreedom I can take a look into it, but that definitely seems to be what I was referring to. I may possibly be able to address @ChildishGiant's issue as well.

**Comment by eagerestwolf** [comment] 2021-12-28 03:32
Status update @fossfreedom, I enabled both of the commented out events (Line 163, destroy on click and Line 184, detroy on loss of focus), and those two events do have the effect of making Lightpad behave more like Launchpad on macOS. Now the question is (and I would like input from @libredeb on this), should this behavior be the default, or should it be opt in? I have no qualms with making some changes to the config code to make it work, I just don't want to make a design decision that should be made by the team that created the application.

**Comment by libredeb** [comment] 2022-02-12 16:38
@eagerestwolf @fossfreedom @justmadethisaccount thank you for the contribution to this project, you awesome people. I've veru busy with my main work lately. 

This issue may have happened when I was debugging another issue and forgot to uncomment it later. Of course the behavior it should have is the closest to macOS Launchpad. Soon I will update these lines in the project and we will release a new version.

Regards!

**Comment by libredeb** [comment] 2022-05-31 04:10
Done!

**Closed** 2022-05-31 04:10 UTC
Labels: bug, enhancement, desktop
